# Generated by Django 3.2.19 on 2023-05-29 14:18

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('contact_type', models.CharField(choices=[('INDIVIDUAL', 'Individual'), ('COMPANY', 'Company')], default='INDIVIDUAL', max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('created_at', models.DateField(default=datetime.date.today)),
                ('updated_at', models.DateField(default=datetime.date.today)),
                ('user', models.ForeignKey(db_column='user', on_delete=django.db.models.deletion.CASCADE, to='Auth.loginuser')),
            ],
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.IntegerField(null=True)),
                ('stage', models.CharField(choices=[('OPPORTUNITY', 'Opportunity'), ('CONTACTED', 'Contacted'), ('NEGOTIATION', 'Negotiation'), ('CLOSED_WON', 'Closed Won'), ('CLOSED_LOST', 'Closed Lost')], default='OPPORTUNITY', max_length=15)),
                ('confidence', models.FloatField()),
                ('closing_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(max_length=250, null=True)),
                ('created_at', models.DateField(default=datetime.date.today)),
                ('updated_at', models.DateField(default=datetime.date.today)),
                ('contact', models.ForeignKey(db_column='contact', on_delete=django.db.models.deletion.CASCADE, to='Pipeline.contact')),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('street', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=20)),
                ('pincode', models.BigIntegerField()),
                ('created_at', models.DateField(default=datetime.date.today)),
                ('updated_at', models.DateField(default=datetime.date.today)),
                ('contact', models.ForeignKey(db_column='contact', on_delete=django.db.models.deletion.CASCADE, to='Pipeline.contact')),
            ],
        ),
    ]
