# Generated by Django 3.2.19 on 2023-05-12 06:07

import Pipeline.constants
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_type', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('created_at', models.DateField(default=datetime.date.today)),
                ('updated_at', models.DateField(default=datetime.date.today)),
                ('user', models.ForeignKey(db_column='user', on_delete=django.db.models.deletion.CASCADE, to='Auth.loginuser')),
            ],
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.IntegerField(null=True)),
                ('stage', models.CharField(choices=[(Pipeline.constants.StageConstant['OPPORTUNITY'], 'Opportunity'), (Pipeline.constants.StageConstant['CONTACTED'], 'Contacted'), (Pipeline.constants.StageConstant['NEGOTIATION'], 'Negotiation'), (Pipeline.constants.StageConstant['CLOSED_WON'], 'Closed Won'), (Pipeline.constants.StageConstant['CLOSED_LOST'], 'Closed Lost')], default=Pipeline.constants.StageConstant['OPPORTUNITY'], max_length=15)),
                ('confidence', models.IntegerField()),
                ('closing_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(max_length=250, null=True)),
                ('customer', models.ForeignKey(db_column='customer', on_delete=django.db.models.deletion.CASCADE, to='Pipeline.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('street', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=20)),
                ('pincode', models.BigIntegerField()),
                ('created_at', models.DateField(default=datetime.date.today)),
                ('updated_at', models.DateField(default=datetime.date.today)),
                ('customer', models.ForeignKey(db_column='customer', on_delete=django.db.models.deletion.CASCADE, to='Pipeline.customer')),
            ],
        ),
        migrations.AddConstraint(
            model_name='lead',
            constraint=models.CheckConstraint(check=models.Q(('confidence__gte', 0), ('confidence__lte', 1)), name='Confidence Range Check'),
        ),
    ]
