# Generated by Django 3.2.19 on 2023-05-18 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pipeline', '0003_auto_20230516_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='stage',
            field=models.CharField(choices=[('OPPORTUNITY', 'Opportunity'), ('CONTACTED', 'Contacted'), ('NEGOTIATION', 'Negotiation'), ('CLOSED_WON', 'Closed Won'), ('CLOSED_LOST', 'Closed Lost')], default='OPPORTUNITY', max_length=15),
        ),
    ]
