# Generated by Django 3.2.19 on 2023-05-24 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pipeline', '0004_alter_lead_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='amount_paid',
            field=models.IntegerField(default=0),
        ),
    ]
