# Generated by Django 3.2.19 on 2023-05-27 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pipeline', '0006_auto_20230524_1046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='amount_paid',
        ),
    ]
