# Generated by Django 3.2.19 on 2023-05-12 06:07

import Projects.constants
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Pipeline', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('value', models.IntegerField()),
                ('priority', models.CharField(choices=[(Projects.constants.PriorityConstant['LOW'], 'Low'), (Projects.constants.PriorityConstant['MEDIUM'], 'Medium'), (Projects.constants.PriorityConstant['HIGH'], 'High')], default=Projects.constants.PriorityConstant['LOW'], max_length=15)),
                ('start_date', models.DateField(default=datetime.date.today)),
                ('due_date', models.DateField(null=True)),
                ('status', models.CharField(choices=[(Projects.constants.StatusConstant['INCOMPLETE'], 'Incomplete'), (Projects.constants.StatusConstant['COMPLETE'], 'Complete')], default=Projects.constants.StatusConstant['INCOMPLETE'], max_length=15)),
                ('created_at', models.DateField(default=datetime.date.today)),
                ('updated_at', models.DateField(default=datetime.date.today)),
                ('amount_paid', models.IntegerField(default=0)),
                ('lead', models.ForeignKey(db_column='lead', on_delete=django.db.models.deletion.CASCADE, to='Pipeline.lead')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('priority', models.CharField(choices=[(Projects.constants.PriorityConstant['LOW'], 'Low'), (Projects.constants.PriorityConstant['MEDIUM'], 'Medium'), (Projects.constants.PriorityConstant['HIGH'], 'High')], default=Projects.constants.PriorityConstant['LOW'], max_length=15)),
                ('status', models.CharField(choices=[(Projects.constants.StatusConstant['INCOMPLETE'], 'Incomplete'), (Projects.constants.StatusConstant['COMPLETE'], 'Complete')], default=Projects.constants.StatusConstant['INCOMPLETE'], max_length=15)),
                ('project', models.ForeignKey(db_column='project', on_delete=django.db.models.deletion.CASCADE, to='Projects.project')),
            ],
        ),
    ]
