# Generated by Django 3.2.19 on 2023-05-29 14:18

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Pipeline', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('value', models.IntegerField()),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='LOW', max_length=15)),
                ('start_date', models.DateField()),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('INCOMPLETE', 'Incomplete'), ('COMPLETE', 'Complete')], default='INCOMPLETE', max_length=15)),
                ('created_at', models.DateField(default=datetime.date.today)),
                ('updated_at', models.DateField(default=datetime.date.today)),
                ('contact', models.ForeignKey(db_column='contact', on_delete=django.db.models.deletion.CASCADE, to='Pipeline.contact')),
                ('lead', models.ForeignKey(db_column='lead', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Pipeline.lead')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='LOW', max_length=15)),
                ('status', models.CharField(choices=[('INCOMPLETE', 'Incomplete'), ('COMPLETE', 'Complete')], default='INCOMPLETE', max_length=15)),
                ('start_date', models.DateField()),
                ('due_date', models.DateField()),
                ('project', models.ForeignKey(db_column='project', on_delete=django.db.models.deletion.CASCADE, to='Projects.project')),
            ],
        ),
    ]
