# Generated by Django 4.2.2 on 2023-06-26 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Pipeline', '0002_alter_contact_email'),
        ('Auth', '0002_auto_20230601_1030'),
        ('Projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='due_date',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='task',
            name='start_date',
        ),
        migrations.AddField(
            model_name='task',
            name='contact',
            field=models.ForeignKey(db_column='contact', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Pipeline.contact'),
        ),
        migrations.AddField(
            model_name='task',
            name='user',
            field=models.ForeignKey(db_column='user', default=1, on_delete=django.db.models.deletion.CASCADE, to='Auth.loginuser'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='project',
            field=models.ForeignKey(db_column='project', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Projects.project'),
        ),
    ]
