# Generated by Django 4.2.2 on 2023-06-28 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0002_rename_due_date_task_date_remove_task_start_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('IN_PROGRESS', 'In Progress'), ('COMPLETE', 'Complete')], default='NOT_STARTED', max_length=15),
        ),
        migrations.AlterField(
            model_name='project',
            name='value',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('IN_PROGRESS', 'In Progress'), ('COMPLETE', 'Complete')], default='NOT_STARTED', max_length=15),
        ),
    ]
