# Generated by Django 3.2.19 on 2023-05-24 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0003_auto_20230518_1158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='amount_paid',
        ),
    ]
