# Generated by Django 3.2.19 on 2023-06-22 04:04

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0001_initial'),
        ('Assets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='filename',
            field=models.CharField(default='null', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='asset',
            name='project',
            field=models.ForeignKey(db_column='project', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Projects.project'),
        ),
        migrations.AddField(
            model_name='asset',
            name='updated_at',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
