# Generated by Django 3.2.19 on 2023-05-26 05:39

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields
import timezone_field.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Auth', '0004_auto_20230526_1109'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(db_column='user', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Auth.loginuser')),
                ('legal_name', models.CharField(max_length=20, null=True)),
                ('entity', models.CharField(max_length=10, null=True)),
                ('country', models.CharField(max_length=20, null=True)),
                ('state', models.CharField(max_length=20, null=True)),
                ('currency', models.CharField(max_length=10, null=True)),
                ('timezone', timezone_field.fields.TimeZoneField(null=True)),
                ('address', models.TextField(max_length=50, null=True)),
                ('city', models.CharField(max_length=20, null=True)),
                ('pincode', models.IntegerField(null=True)),
                ('phone_no', phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None, unique=True)),
            ],
        ),
    ]
