# Generated by Django 4.2.2 on 2023-06-26 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0002_auto_20230601_1030'),
        ('Profile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Integrations',
            fields=[
                ('user', models.OneToOneField(db_column='user', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Auth.loginuser')),
                ('calender_integration', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
