# Generated by Django 4.2.2 on 2023-06-27 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0002_integrations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integrations',
            name='calender_integration',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
