# Generated by Django 4.2.2 on 2023-06-30 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0003_alter_integrations_calender_integration'),
    ]

    operations = [
        migrations.AddField(
            model_name='integrations',
            name='zoom_integration',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
