# Generated by Django 4.2.2 on 2023-06-30 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0004_integrations_zoom_integration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integrations',
            name='zoom_integration',
            field=models.CharField(max_length=600, null=True),
        ),
    ]
