# Generated by Django 4.2.2 on 2023-07-07 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0005_alter_integrations_zoom_integration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='phone_no',
        ),
    ]
