# Generated by Django 3.2.19 on 2023-05-12 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginuser',
            name='password',
            field=models.BinaryField(editable=True),
        ),
    ]
