# Generated by Django 3.2.19 on 2023-05-16 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0002_alter_loginuser_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginuser',
            name='username',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
