# Generated by Django 3.2.19 on 2023-05-26 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0003_alter_loginuser_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loginuser',
            name='phone_no',
        ),
        migrations.AlterField(
            model_name='loginuser',
            name='password',
            field=models.BinaryField(editable=True, null=True),
        ),
        migrations.AlterField(
            model_name='loginuser',
            name='username',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
    ]
