# Generated by Django 4.2.2 on 2023-07-08 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0003_loginuser_company_loginuser_phone_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginuser',
            name='password',
            field=models.BinaryField(editable=True),
        ),
        migrations.AlterField(
            model_name='loginuser',
            name='username',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
