# Generated by Django 3.2.19 on 2023-06-01 05:00

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Pipeline', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=20)),
                ('description', models.TextField(max_length=250, null=True)),
                ('date', models.DateField(default=datetime.date.today)),
                ('status', models.CharField(choices=[('INCOMPLETE', 'Incomplete'), ('COMPLETE', 'Complete')], default='INCOMPLETE', max_length=15)),
                ('link', models.URLField(null=True)),
                ('contact', models.ForeignKey(db_column='contact', on_delete=django.db.models.deletion.CASCADE, to='Pipeline.contact')),
            ],
        ),
    ]
