# Generated by Django 4.2.2 on 2023-06-26 11:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Calender', '0002_remove_event_date_event_due_date_event_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='due_date',
        ),
        migrations.RemoveField(
            model_name='event',
            name='start_date',
        ),
        migrations.AddField(
            model_name='event',
            name='due',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 26, 17, 5, 56, 143449)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 26, 17, 5, 59, 839014)),
            preserve_default=False,
        ),
    ]
