# Generated by Django 4.2.2 on 2023-06-27 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Calender', '0003_remove_event_due_date_remove_event_start_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='calender_event_id',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
