# Generated by Django 4.2.2 on 2023-06-28 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Calender', '0004_event_calender_event_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='calender_event_link',
            field=models.URLField(null=True),
        ),
    ]
