# Generated by Django 3.2.19 on 2023-05-29 14:18

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Pipeline', '0001_initial'),
        ('Projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.IntegerField()),
                ('date', models.DateField(default=datetime.date.today)),
                ('contact', models.ForeignKey(db_column='contact', on_delete=django.db.models.deletion.CASCADE, to='Pipeline.contact')),
                ('lead', models.ForeignKey(db_column='lead', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Pipeline.lead')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount_received', models.IntegerField()),
                ('date', models.DateField(default=datetime.date.today)),
                ('contact', models.ForeignKey(db_column='contact', on_delete=django.db.models.deletion.CASCADE, to='Pipeline.contact')),
                ('project', models.ForeignKey(db_column='project', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.IntegerField()),
                ('date', models.DateField(default=datetime.date.today)),
                ('contact', models.ForeignKey(db_column='contact', on_delete=django.db.models.deletion.CASCADE, to='Pipeline.contact')),
                ('project', models.ForeignKey(db_column='project', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Projects.project')),
            ],
        ),
    ]
