# Generated by Django 3.2.19 on 2023-05-12 06:07

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Projects', '0001_initial'),
        ('Pipeline', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.IntegerField()),
                ('date', models.DateField(default=datetime.date.today)),
                ('lead', models.ForeignKey(db_column='lead', on_delete=django.db.models.deletion.CASCADE, to='Pipeline.lead')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount_received', models.IntegerField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.IntegerField()),
                ('due_date', models.DateField()),
                ('lead', models.ForeignKey(db_column='lead', on_delete=django.db.models.deletion.CASCADE, to='Pipeline.lead')),
            ],
        ),
    ]
