# Generated by Django 3.2.19 on 2023-05-24 04:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Pipeline', '0005_lead_amount_paid'),
        ('Accounting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pipeline.lead'),
        ),
    ]
