# Generated by Django 4.2.2 on 2023-07-03 12:53

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Accounting', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='date',
            new_name='creation_date',
        ),
        migrations.RenameField(
            model_name='proposal',
            old_name='date',
            new_name='creation_date',
        ),
        migrations.AddField(
            model_name='invoice',
            name='expiry_date',
            field=models.DateField(default=datetime.datetime(2023, 7, 3, 18, 22, 53, 576313)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='invoice_number',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='notes',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='tax',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='proposal',
            name='expiry_date',
            field=models.DateField(default=datetime.datetime(2023, 7, 3, 18, 23, 6, 817353)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proposal',
            name='notes',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='proposal',
            name='proposal_number',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proposal',
            name='tax',
            field=models.IntegerField(null=True),
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('details', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('rate', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('invoice', models.ForeignKey(db_column='invoice', null=True, on_delete=django.db.models.deletion.CASCADE, to='Accounting.invoice')),
                ('proposal', models.ForeignKey(db_column='proposal', null=True, on_delete=django.db.models.deletion.CASCADE, to='Accounting.proposal')),
            ],
        ),
    ]
