# Generated by Django 3.2.19 on 2023-05-24 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounting', '0002_alter_payment_project'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='project',
            new_name='lead',
        ),
    ]
