# Generated by Django 4.2.2 on 2023-07-04 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounting', '0002_rename_date_invoice_creation_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='amount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='tax',
            field=models.FloatField(null=True),
        ),
    ]
