# Generated by Django 3.2.19 on 2023-05-27 11:58

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0008_auto_20230527_0942'),
        ('Accounting', '0004_payment_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='due_date',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='lead',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='lead',
        ),
        migrations.AddField(
            model_name='invoice',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='invoice',
            name='project',
            field=models.ForeignKey(db_column='project', default=1, on_delete=django.db.models.deletion.CASCADE, to='Projects.project'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='project',
            field=models.ForeignKey(db_column='project', default=2, on_delete=django.db.models.deletion.CASCADE, to='Projects.project'),
            preserve_default=False,
        ),
    ]
