# Generated by Django 4.2.2 on 2023-07-05 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounting', '0005_alter_invoice_amount_alter_item_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='amount',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='tax',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='item',
            name='rate',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='tax',
            field=models.FloatField(default=0, null=True),
        ),
    ]
